### ISSUE TITLE
New PA code crashes on generic stress tests at times (few percent of time I would guess)

### ISSUE THREAD

**Issue by fingon** [sbyx/hnetd#36]
SIGSEGV here (clearly ldp is derived from a pointer that is NULL; probably a list header offset or something)

#0  0x000000000041b0c4 in pa_ldp_unassign (ldp=0xffffffffffffffd0)
    at /home/mstenber/component/hnetd/src/pa_core.c:158
#1  0x000000000041cf66 in _pa_dp_del (dp=0x645918)
    at /home/mstenber/component/hnetd/src/pa_core.c:498
#2  0x000000000041d085 in pa_dp_del (dp=0x645918)
    at /home/mstenber/component/hnetd/src/pa_core.c:509
#3  0x0000000000427151 in hpa_dp_set_enabled (hpa=0x645160, dp=0x6458f0, 
    enabled=false) at /home/mstenber/component/hnetd/src/hncp_pa.c:578
#4  0x0000000000427abf in hpa_ula_to (to=0x6458b8)
    at /home/mstenber/component/hnetd/src/hncp_pa.c:764
#5  0x000000000042a281 in hpa_update_dp_tlv (hpa=0x645160, n=0x648ab0, 
    tlv=0x64d01c, add=true)
    at /home/mstenber/component/hnetd/src/hncp_pa.c:1365
#6  0x000000000042a483 in hpa_dncp_tlv_change_cb (s=0x645168, n=0x648ab0, 
    tlv=0x64d018, add=true)
    at /home/mstenber/component/hnetd/src/hncp_pa.c:1399
#7  0x0000000000415617 in dncp_notify_subscribers_tlvs_changed (n=0x648ab0, 
    a_old=0x64dbb0, a_new=0x64cfd0)
    at /home/mstenber/component/hnetd/src/dncp_notify.c:182

**Comment by fingon** [comment]
Hasn't been reproducible recently -> assume testing setup anomaly or something.
